import type { Brand, BusinessSettings, Category, Industry, Product } from "./types";

export const businessSettings: BusinessSettings = {
  businessName: "Starlite Tools",
  legalName: "Starlite Tools Company Limited",
  tagline: "Tools built for work that cannot fail.",
  whatsappNumber: "2348031234567",
  whatsappDisplay: "+234 803 123 4567",
  phoneDisplay: "+234 806 765 4321",
  email: "sales@starlitetools.ng",
  address: "Ochanja Market, Onitsha",
  city: "Onitsha",
  state: "Anambra State",
  country: "Nigeria",
  hours: "Monday – Saturday, 8:00 AM – 6:00 PM",
  yearsInBusiness: "20+",
  productsSupplied: "1000+",
  dealerPartners: "500+",
  coverage: "Nigeria",
};

export const categories: Category[] = [
  { id: "cat-power-tools", name: "Power Tools", slug: "power-tools", description: "Corded and cordless power tools for professional trade use.", productCount: 128 },
  { id: "cat-cordless-tools", name: "Cordless Tools", slug: "cordless-tools", description: "Battery-powered tools built on the P20S platform.", productCount: 84 },
  { id: "cat-hand-tools", name: "Hand Tools", slug: "hand-tools", description: "Wrenches, hammers, pliers and everyday site hand tools.", productCount: 96 },
  { id: "cat-welding", name: "Welding Equipment", slug: "welding-equipment", description: "Arc welders, MIG/TIG equipment and welding accessories.", productCount: 42 },
  { id: "cat-safety", name: "Safety Equipment", slug: "safety-equipment", description: "PPE, helmets, gloves and site safety gear.", productCount: 58 },
  { id: "cat-accessories", name: "Accessories", slug: "accessories", description: "Blades, discs, bits, batteries and chargers.", productCount: 140 },
  { id: "cat-generators", name: "Generators", slug: "generators", description: "Petrol and diesel generators for site and home backup.", productCount: 27 },
  { id: "cat-measuring", name: "Measuring Tools", slug: "measuring-tools", description: "Tapes, levels and layout instruments.", productCount: 33 },
];

export const industries: Industry[] = [
  { id: "ind-construction", name: "Construction", slug: "construction", description: "Site-grade tools for builders and contractors.", productCount: 128 },
  { id: "ind-welding", name: "Welding & Fabrication", slug: "welding-fabrication", description: "Welding machines, rods and fabrication accessories.", productCount: 98 },
  { id: "ind-carpentry", name: "Carpentry & Woodworking", slug: "carpentry-woodworking", description: "Saws, routers and precision woodworking tools.", productCount: 76 },
  { id: "ind-electrical", name: "Electrical Installation", slug: "electrical-installation", description: "Tools and testers for electrical installation work.", productCount: 64 },
];

export const brands: Brand[] = [
  { id: "brand-ingco", name: "INGCO", slug: "ingco", description: "Original INGCO power tools, hand tools and accessories." },
  { id: "brand-total", name: "TOTAL", slug: "total", description: "TOTAL Tools — durable equipment for trade and industry." },
  { id: "brand-bosch", name: "BOSCH", slug: "bosch", description: "Bosch professional power tools." },
  { id: "brand-makita", name: "MAKITA", slug: "makita", description: "Makita cordless and corded professional tools." },
  { id: "brand-dewalt", name: "DEWALT", slug: "dewalt", description: "DeWalt heavy-duty jobsite tools." },
];

export const products: Product[] = [
  {
    id: "p-cordless-drill",
    name: "INGCO 20V Brushless Cordless Drill",
    slug: "ingco-20v-brushless-cordless-drill",
    sku: "COLI20024",
    model: "COLI20024",
    brandId: "brand-ingco",
    categoryId: "cat-cordless-tools",
    industryIds: ["ind-construction", "ind-carpentry"],
    shortDescription: "High performance brushless motor delivers maximum power and longer runtime.",
    description:
      "The INGCO 20V Brushless Cordless Drill is engineered for professional performance. With 55Nm torque, 2-speed gearbox, and all-metal chuck, it is ideal for construction, carpentry, maintenance and industrial applications. Part of the P20S One Platform, More Ways to Work system.",
    specs: [
      { label: "Voltage", value: "20V MAX" },
      { label: "Torque", value: "55 Nm" },
      { label: "No-load Speed", value: "0-150 / 0-2100 RPM" },
      { label: "Chuck Size", value: "13 mm" },
      { label: "Weight", value: "1.2 KG" },
      { label: "Battery System", value: "P20S — One Battery, Multiple Tools" },
    ],
    included: ["1x Drill body", "1x 20V 2.0Ah battery", "1x Charger", "1x Carry case"],
    availabilityStatus: "in_stock",
    isFeatured: true,
    voltage: "20V",
  },
  {
    id: "p-angle-grinder-cordless",
    name: "INGCO 20V Angle Grinder",
    slug: "ingco-20v-angle-grinder",
    sku: "CAGLI20018",
    model: "CAGLI20018",
    brandId: "brand-ingco",
    categoryId: "cat-cordless-tools",
    industryIds: ["ind-construction", "ind-welding"],
    shortDescription: "Cordless cutting and grinding power for metalwork and site fabrication.",
    description:
      "A 100mm cordless angle grinder built on the P20S platform for cutting, grinding and surface prep without a power cable. Suited to welding shops, site fabrication and general metalwork.",
    specs: [
      { label: "Voltage", value: "20V MAX" },
      { label: "Disc Diameter", value: "100 mm" },
      { label: "No-load Speed", value: "10,000 RPM" },
      { label: "Spindle Thread", value: "M10" },
      { label: "Weight", value: "1.4 KG" },
    ],
    included: ["1x Grinder body", "1x Guard", "1x Auxiliary handle", "1x Spanner"],
    availabilityStatus: "in_stock",
    isFeatured: true,
    voltage: "20V",
  },
  {
    id: "p-rotary-hammer",
    name: "INGCO 20V Rotary Hammer",
    slug: "ingco-20v-rotary-hammer",
    sku: "CRHLI20018",
    model: "CRHLI20018",
    brandId: "brand-ingco",
    categoryId: "cat-cordless-tools",
    industryIds: ["ind-construction", "ind-electrical"],
    shortDescription: "2.0 Joule cordless rotary hammer for masonry drilling and light chiselling.",
    description:
      "Cordless SDS-Plus rotary hammer delivering 2.0J impact energy for concrete drilling, wall chasing and light chiselling on site, without being tethered to a generator.",
    specs: [
      { label: "Voltage", value: "20V MAX" },
      { label: "Impact Energy", value: "2.0 J" },
      { label: "Chuck", value: "SDS-Plus" },
      { label: "Impact Rate", value: "0-4,500 BPM" },
      { label: "Weight", value: "2.6 KG" },
    ],
    included: ["1x Hammer body", "1x Side handle", "1x Depth rod", "1x Case"],
    availabilityStatus: "in_stock",
    isFeatured: true,
    voltage: "20V",
  },
  {
    id: "p-impact-driver",
    name: "INGCO 20V Cordless Impact Driver",
    slug: "ingco-20v-cordless-impact-driver",
    sku: "CIDLI20621",
    model: "CIDLI20621",
    brandId: "brand-ingco",
    categoryId: "cat-cordless-tools",
    industryIds: ["ind-construction", "ind-carpentry"],
    shortDescription: "Compact high-torque impact driver for fast fastening on site.",
    description:
      "A compact 1/4-inch hex impact driver for driving screws and bolts quickly under load. Lightweight design reduces fatigue during long fastening runs.",
    specs: [
      { label: "Voltage", value: "20V MAX" },
      { label: "Max Torque", value: "180 Nm" },
      { label: "Chuck", value: "1/4\" Hex Quick-Change" },
      { label: "No-load Speed", value: "0-2,800 RPM" },
      { label: "Weight", value: "1.1 KG" },
    ],
    included: ["1x Driver body", "1x Belt clip", "1x Case"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: "20V",
  },
  {
    id: "p-circular-saw",
    name: "INGCO 20V Circular Saw",
    slug: "ingco-20v-circular-saw",
    sku: "CSLI20018",
    model: "CSLI20018",
    brandId: "brand-ingco",
    categoryId: "cat-cordless-tools",
    industryIds: ["ind-carpentry", "ind-construction"],
    shortDescription: "Cordless circular saw for framing, sheet stock and site cutting.",
    description:
      "A 150mm cordless circular saw built for framing carpenters and site crews who need clean, repeatable cuts without running a cable across the floor.",
    specs: [
      { label: "Voltage", value: "20V MAX" },
      { label: "Blade Diameter", value: "150 mm" },
      { label: "No-load Speed", value: "3,700 RPM" },
      { label: "Max Cut Depth", value: "45 mm @ 90°" },
      { label: "Weight", value: "2.3 KG" },
    ],
    included: ["1x Saw body", "1x TCT blade", "1x Rip fence", "1x Allen key"],
    availabilityStatus: "low_stock",
    isFeatured: false,
    voltage: "20V",
  },
  {
    id: "p-reciprocating-saw",
    name: "INGCO 20V Reciprocating Saw",
    slug: "ingco-20v-reciprocating-saw",
    sku: "RSCLI20018",
    model: "RSCLI20018",
    brandId: "brand-ingco",
    categoryId: "cat-cordless-tools",
    industryIds: ["ind-construction", "ind-carpentry"],
    shortDescription: "Tool-free blade change reciprocating saw for demolition and pipe cutting.",
    description:
      "Variable-speed cordless reciprocating saw for demolition, rough carpentry and pipe cutting. Tool-free blade clamp allows fast blade changes on site.",
    specs: [
      { label: "Voltage", value: "20V MAX" },
      { label: "Stroke Length", value: "20 mm" },
      { label: "Strokes per Minute", value: "0-3,000 SPM" },
      { label: "Blade Change", value: "Tool-free" },
      { label: "Weight", value: "2.1 KG" },
    ],
    included: ["1x Saw body", "2x Blades", "1x Case"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: "20V",
  },
  {
    id: "p-impact-wrench",
    name: "INGCO 20V Cordless Impact Wrench",
    slug: "ingco-20v-cordless-impact-wrench",
    sku: "CIWLI20028",
    model: "CIWLI20028",
    brandId: "brand-ingco",
    categoryId: "cat-cordless-tools",
    industryIds: ["ind-construction"],
    shortDescription: "1/2-inch square drive impact wrench for heavy fastening work.",
    description:
      "Heavy-duty cordless impact wrench with 1/2-inch square drive for structural bolting, vehicle maintenance and heavy fastening jobs.",
    specs: [
      { label: "Voltage", value: "20V MAX" },
      { label: "Max Torque", value: "280 Nm" },
      { label: "Drive", value: "1/2\" Square" },
      { label: "No-load Speed", value: "0-2,400 RPM" },
      { label: "Weight", value: "1.8 KG" },
    ],
    included: ["1x Wrench body", "1x Case"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: "20V",
  },
  {
    id: "p-jigsaw",
    name: "INGCO Cordless Jigsaw",
    slug: "ingco-cordless-jigsaw",
    sku: "CJSLI20018",
    model: "CJSLI20018",
    brandId: "brand-ingco",
    categoryId: "cat-cordless-tools",
    industryIds: ["ind-carpentry"],
    shortDescription: "Variable-speed jigsaw for curved cuts in wood, board and light metal.",
    description:
      "Cordless jigsaw with variable speed control and tool-free blade change, suited to curved cuts, cut-outs and finish carpentry work.",
    specs: [
      { label: "Voltage", value: "20V MAX" },
      { label: "Stroke Length", value: "20 mm" },
      { label: "Max Cut Depth (Wood)", value: "65 mm" },
      { label: "Weight", value: "1.5 KG" },
    ],
    included: ["1x Jigsaw body", "1x Blade", "1x Anti-splinter guard"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: "20V",
  },
  {
    id: "p-hammer-drill-corded",
    name: "TOTAL Corded Hammer Drill",
    slug: "total-corded-hammer-drill",
    sku: "TG1131266",
    model: "TG1131266",
    brandId: "brand-total",
    categoryId: "cat-power-tools",
    industryIds: ["ind-construction", "ind-electrical"],
    shortDescription: "1300W corded hammer drill for heavy masonry and concrete drilling.",
    description:
      "A mains-powered hammer drill built for continuous, heavy-duty masonry drilling on commercial sites where cordless runtime is not practical.",
    specs: [
      { label: "Power", value: "1300 W" },
      { label: "Chuck", value: "13 mm Keyed" },
      { label: "No-load Speed", value: "0-3,000 RPM" },
      { label: "Impact Rate", value: "0-48,000 BPM" },
      { label: "Weight", value: "3.2 KG" },
    ],
    included: ["1x Drill body", "1x Side handle", "1x Depth gauge"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: null,
  },
  {
    id: "p-angle-grinder-bosch",
    name: "BOSCH Professional Angle Grinder",
    slug: "bosch-professional-angle-grinder",
    sku: "GWS-750-100",
    model: "GWS 750-100",
    brandId: "brand-bosch",
    categoryId: "cat-power-tools",
    industryIds: ["ind-construction", "ind-welding"],
    shortDescription: "750W corded angle grinder for continuous cutting and grinding.",
    description:
      "Bosch Professional corded angle grinder built for reliable, all-day cutting and grinding in fabrication shops and on construction sites.",
    specs: [
      { label: "Power", value: "750 W" },
      { label: "Disc Diameter", value: "100 mm" },
      { label: "No-load Speed", value: "12,000 RPM" },
      { label: "Weight", value: "1.8 KG" },
    ],
    included: ["1x Grinder body", "1x Guard", "1x Auxiliary handle"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: null,
  },
  {
    id: "p-screwdriver-makita",
    name: "MAKITA Cordless Screwdriver",
    slug: "makita-cordless-screwdriver",
    sku: "DF012DSE",
    model: "DF012DSE",
    brandId: "brand-makita",
    categoryId: "cat-cordless-tools",
    industryIds: ["ind-carpentry", "ind-electrical"],
    shortDescription: "Compact cordless screwdriver for panel assembly and fixture work.",
    description:
      "A compact, lightweight cordless screwdriver suited to panel building, fixture installation and light assembly work where a full drill is unnecessary.",
    specs: [
      { label: "Voltage", value: "7.2V" },
      { label: "Chuck", value: "1/4\" Hex" },
      { label: "No-load Speed", value: "0-200 / 0-650 RPM" },
      { label: "Weight", value: "0.6 KG" },
    ],
    included: ["1x Driver body", "1x Battery", "1x Charger", "1x Case"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: "7.2V",
  },
  {
    id: "p-demolition-hammer-dewalt",
    name: "DEWALT Demolition Hammer",
    slug: "dewalt-demolition-hammer",
    sku: "D25899K",
    model: "D25899K",
    brandId: "brand-dewalt",
    categoryId: "cat-power-tools",
    industryIds: ["ind-construction"],
    shortDescription: "Heavy-duty SDS-Max demolition hammer for concrete breaking.",
    description:
      "A heavy-duty demolition hammer for breaking concrete, chasing walls and general jobsite demolition. Built for daily commercial use.",
    specs: [
      { label: "Power", value: "1600 W" },
      { label: "Chuck", value: "SDS-Max" },
      { label: "Impact Energy", value: "17.5 J" },
      { label: "Weight", value: "11.6 KG" },
    ],
    included: ["1x Hammer body", "1x Chisel", "1x Point", "1x Case"],
    availabilityStatus: "low_stock",
    isFeatured: false,
    voltage: null,
  },
  {
    id: "p-welding-machine",
    name: "INGCO Inverter Arc Welding Machine",
    slug: "ingco-inverter-arc-welding-machine",
    sku: "MMA20508",
    model: "MMA20508",
    brandId: "brand-ingco",
    categoryId: "cat-welding",
    industryIds: ["ind-welding"],
    shortDescription: "Portable 200A inverter welder for site and workshop fabrication.",
    description:
      "A portable single-phase inverter arc welder delivering up to 200A output, suited to workshop fabrication, site repairs and general steel welding.",
    specs: [
      { label: "Output Current", value: "20-200 A" },
      { label: "Input", value: "220-240V, 50/60Hz" },
      { label: "Electrode Diameter", value: "1.6-4.0 mm" },
      { label: "Duty Cycle", value: "60% @ 160A" },
      { label: "Weight", value: "4.8 KG" },
    ],
    included: ["1x Welding machine", "1x Electrode holder", "1x Earth clamp", "1x Carry strap"],
    availabilityStatus: "in_stock",
    isFeatured: true,
    voltage: null,
  },
  {
    id: "p-welding-helmet",
    name: "INGCO Auto-Darkening Welding Helmet",
    slug: "ingco-auto-darkening-welding-helmet",
    sku: "AWH011",
    model: "AWH011",
    brandId: "brand-ingco",
    categoryId: "cat-safety",
    industryIds: ["ind-welding"],
    shortDescription: "Auto-darkening welding helmet with adjustable shade for arc and MIG work.",
    description:
      "Auto-darkening welding helmet protecting the operator's eyes and face during arc and MIG welding, with adjustable sensitivity and shade level.",
    specs: [
      { label: "Shade Range", value: "DIN 9-13" },
      { label: "Switching Time", value: "1/25,000 sec" },
      { label: "Power", value: "Solar + Battery" },
      { label: "Weight", value: "0.5 KG" },
    ],
    included: ["1x Helmet", "1x Spare lens cover"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: null,
  },
  {
    id: "p-safety-gloves",
    name: "INGCO Heavy-Duty Safety Gloves",
    slug: "ingco-heavy-duty-safety-gloves",
    sku: "HGV01",
    model: "HGV01",
    brandId: "brand-ingco",
    categoryId: "cat-safety",
    industryIds: ["ind-construction", "ind-welding"],
    shortDescription: "Cut-resistant, reinforced-palm gloves for site and workshop use.",
    description:
      "Durable work gloves with reinforced palm and cut-resistant lining, suited to general site work, material handling and workshop tasks.",
    specs: [
      { label: "Material", value: "Synthetic leather + spandex" },
      { label: "Sizes", value: "M / L / XL" },
      { label: "Cut Resistance", value: "Level 3" },
    ],
    included: ["1x Pair of gloves"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: null,
  },
  {
    id: "p-generator",
    name: "TOTAL Petrol Generator 5.5KVA",
    slug: "total-petrol-generator-5-5kva",
    sku: "TP1550001",
    model: "TP1550001",
    brandId: "brand-total",
    categoryId: "cat-generators",
    industryIds: ["ind-construction"],
    shortDescription: "5.5KVA petrol generator for site power and backup supply.",
    description:
      "A 5.5KVA air-cooled petrol generator suited to powering site tools, small workshops, and backup supply for shops and offices.",
    specs: [
      { label: "Rated Output", value: "5.0 KVA" },
      { label: "Max Output", value: "5.5 KVA" },
      { label: "Fuel", value: "Petrol" },
      { label: "Tank Capacity", value: "15 L" },
      { label: "Weight", value: "45 KG" },
    ],
    included: ["1x Generator", "1x Tool kit", "1x Manual"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: null,
  },
  {
    id: "p-wrench-set",
    name: "INGCO 46-Piece Hand Tool Set",
    slug: "ingco-46-piece-hand-tool-set",
    sku: "HKTB114681",
    model: "HKTB114681",
    brandId: "brand-ingco",
    categoryId: "cat-hand-tools",
    industryIds: ["ind-construction", "ind-carpentry"],
    shortDescription: "46-piece general purpose hand tool set in a carry case.",
    description:
      "A 46-piece hand tool kit covering wrenches, sockets, pliers, screwdrivers and general fasteners — a practical starter set for site or workshop.",
    specs: [
      { label: "Pieces", value: "46" },
      { label: "Case", value: "Blow-moulded carry case" },
      { label: "Material", value: "Chrome vanadium steel" },
    ],
    included: ["1x Tool case with 46 pieces"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: null,
  },
  {
    id: "p-spirit-level",
    name: "INGCO Aluminium Spirit Level 600mm",
    slug: "ingco-aluminium-spirit-level-600mm",
    sku: "HSL086002",
    model: "HSL086002",
    brandId: "brand-ingco",
    categoryId: "cat-measuring",
    industryIds: ["ind-construction", "ind-carpentry"],
    shortDescription: "600mm aluminium spirit level with 3 vials for site layout work.",
    description:
      "Lightweight aluminium spirit level with horizontal, vertical and 45-degree vials for accurate layout and alignment on site.",
    specs: [
      { label: "Length", value: "600 mm" },
      { label: "Material", value: "Aluminium" },
      { label: "Vials", value: "3" },
      { label: "Accuracy", value: "±0.5 mm/m" },
    ],
    included: ["1x Spirit level"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: null,
  },
  {
    id: "p-measuring-tape",
    name: "INGCO Steel Measuring Tape 8m",
    slug: "ingco-steel-measuring-tape-8m",
    sku: "HSMT08081",
    model: "HSMT08081",
    brandId: "brand-ingco",
    categoryId: "cat-measuring",
    industryIds: ["ind-construction", "ind-carpentry", "ind-electrical"],
    shortDescription: "8-metre steel measuring tape with rubber-coated case.",
    description:
      "Durable 8m steel measuring tape with a rubber-coated, impact-resistant case and a strong return spring, built for daily site use.",
    specs: [
      { label: "Length", value: "8 m" },
      { label: "Blade Width", value: "25 mm" },
      { label: "Case", value: "Rubber-coated ABS" },
    ],
    included: ["1x Measuring tape"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: null,
  },
  {
    id: "p-cutting-disc",
    name: "INGCO Metal Cutting Disc 4.5\" (Pack of 10)",
    slug: "ingco-metal-cutting-disc-pack-of-10",
    sku: "MCD1512",
    model: "MCD1512",
    brandId: "brand-ingco",
    categoryId: "cat-accessories",
    industryIds: ["ind-construction", "ind-welding"],
    shortDescription: "4.5-inch metal cutting discs for angle grinders, pack of 10.",
    description:
      "A 10-pack of 4.5-inch metal cutting discs for angle grinders, suited to steel bar, sheet and pipe cutting on site or in the workshop.",
    specs: [
      { label: "Diameter", value: "115 mm (4.5\")" },
      { label: "Bore", value: "22.2 mm" },
      { label: "Thickness", value: "1.2 mm" },
      { label: "Pack Size", value: "10 discs" },
    ],
    included: ["10x Cutting discs"],
    availabilityStatus: "in_stock",
    isFeatured: false,
    voltage: null,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getBrand(brandId: string): Brand | undefined {
  return brands.find((b) => b.id === brandId);
}

export function getCategory(categoryId: string): Category | undefined {
  return categories.find((c) => c.id === categoryId);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getIndustryBySlug(slug: string): Industry | undefined {
  return industries.find((i) => i.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.categoryId === product.categoryId)
    .slice(0, limit);
}
